"""add employer relationship to jobs

Revision ID: 5a3e796c4ab9
Revises: 8742b554e5a2
Create Date: 2026-03-29 18:24:34.828757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a3e796c4ab9'
down_revision = '8742b554e5a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employer_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_jobs_employer_id'), 'users', ['employer_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_picture')

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_jobs_employer_id'), type_='foreignkey')
        batch_op.drop_column('employer_id')

    # ### end Alembic commands ###
