"""add status field

Revision ID: 8742b554e5a2
Revises: 7ed5df876af3
Create Date: 2026-03-17 13:55:53.003144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8742b554e5a2'
down_revision = '7ed5df876af3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(), nullable=True))

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.alter_column('company',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('job_title',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.create_unique_constraint(batch_op.f('uq_users_email'), ['email'])
        batch_op.drop_column('profile_picture')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture', sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_users_email'), type_='unique')
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.alter_column('job_title',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('company',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
